spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthmanagement
    username: ${databaseusername}
    password: ${databasepassword}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  messages:
    basename: No Env Specified
management:
  endpoints:
    web:
      exposure:
        include: '*'
